services:
  postgres:
    image: postgres:alpine
    container_name: PostgreSQL
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data # Linux is case sensitive, so table name cases should be consistent!
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env # This will override the .env files in the backend/frontend folder
    depends_on:
      - postgres
    tty: true # Keep the container "always running". Prevent <Container> exited with code 0 error

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    env_file:
      - .env # This will override the .env files in the backend/frontend folder
    depends_on:
      - backend

volumes:
  postgres-data:
